In [4]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [7]:
print(np.zeros((3, 3)))
print(np.ones((2, 4)))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.rand(3, 2))
print(np.random.randn(3, 2))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.23080635 0.89190409]
 [0.31504601 0.03732305]
 [0.22439948 0.63803924]]
[[ 0.11552756  0.24520878]
 [-0.32879839  0.12125377]
 [-1.24783944 -0.23893652]]


In [18]:
print(np.random.randint(1,10))

6


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(np.sin(a))

[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]


In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
#print(A@B)


 

[[19 22]
 [43 50]]


In [29]:
arr = np.array([1, 2, 3, 4])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

10
2.5
4
1
1.118033988749895


In [30]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1:4])
print(arr[::2])

1
[2 3 4]
[1 3 5]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:, 1])
print(arr[1, :2])

2
[2 5]
[4 5]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(arr[mask])

[4 5]


In [37]:
arr = np.arange(9)
print(arr.reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


In [40]:
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
a = np.array([1, 2, 3])
a + 5  # [6, 7, 8]